name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:rr)

variables:
  RepoName: AzurePoliciesLabSolutions
  FolderPath: Templates/Assignments #change it you didn't follow our suggested path
  ArtifactName: assignments
  GitHubServiceConnectionName: alguadam

resources:
  repositories:
    - repository: main
      type: github
      name: '$(RepoName)'
      endpoint: '$(GitHubServiceConnectionName)'

trigger: #continuous integration will be enabled for all branches and the path containing the ARM template
  branches:
    include:
      - '*'
  paths:
    include:
      - Templates/Assignments #change it you didn't follow our suggested path

jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: ubuntu-16.04
  workspace:
    clean: all
  
  steps:
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Template Files as Azure DevOps artifact'
    inputs:
      PathtoPublish: $(FolderPath)
      ArtifactName: $(ArtifactName)